### PR TITLE
handle subxt error and update lighthouse

### LINKED ISSUE #54: [ISSUE] Handle subxt errors returning all metadata along with error
## Overview
Subxt errors are not parsed correctly and they return errors including all the metadata.

Error : 
```
Runtime(Module(ModuleError { metadata: Metadata { 
inner: Metadata { types: PortableRegistry { types: [
PortableType { id: 0, ty: Type { path: Path { segments: ["sp_core", "crypto", "AccountId32"] }, type_params: [], type_def: 
.
.
raw: RawModuleError { pallet_index: 41, error: [0, 0, 0, 0] } }))
```

Expect Error : Pallet AlreadyInitialized

### LINKED ISSUE #60: [TASK] Use node url from config to connect with client node
## Overview
Currently, the client connects to the default node locally running node on `ws://127.0.0.1:9944`. Instead, we should use the substrate URL from the config file to form a connection with the node.

```rust
let api = OnlineClient<PolkadotConfig> = OnlineClient::<PolkadotConfig>::from_url(config.substrate_url).await?;
```

### LINKED ISSUE #61: [ISSUE] Dependency conflict for libsqlite3-sys used by Lighthouse and Tangle
## Overview

We probably need to update lighthouse dependencies to match with the one required by Tangle inorder to run with it.

```
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `rusqlite v0.28.0`
    ... which satisfies dependency `rusqlite = "^0.28.0"` of package `types v0.2.1 (https://github.com/webb-tools/lighthouse.git#dfcb3363)`
    ... which satisfies git dependency `types` of package `eth2-to-substrate-relay v0.1.0 (https://github.com/webb-tools/pallet-eth2-light-client?tag=v0.4.3#c089a76d)`
    ... which satisfies git dependency `eth2-to-substrate-relay` of package `pallet-eth2-light-client-relayer-gadget v0.0.1 (https://github.com/webb-tools/pallet-eth2-light-client?tag=v0.4.3#c089a76d)`
    ... which satisfies git dependency `pallet-eth2-light-client-relayer-gadget` of package `tangle-standalone v0.4.2 (/Users/salman01zz/Webb-Tools/tangle/standalone/node)`
versions that meet the requirements `^0.25.0` are: 0.25.2, 0.25.1, 0.25.0

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.26.0`
    ... which satisfies dependency `libsqlite3-sys = "^0.26.0"` (locked to 0.26.0) of package `sqlx-sqlite v0.7.1`
    ... which satisfies dependency `sqlx-sqlite = "=0.7.1"` (locked to 0.7.1) of package `sqlx v0.7.1`
    ... which satisfies dependency `sqlx = "^0.7.1"` (locked to 0.7.1) of package `fc-db v2.0.0-dev (https://github.com/paritytech/frontier.git?branch=polkadot-v1.0.0#b520b749)`
    ... which satisfies git dependency `fc-db` (locked to 2.0.0-dev) of package `fc-cli v1.0.0-dev (https://github.com/paritytech/frontier.git?branch=polkadot-v1.0.0#b520b749)`
    ... which satisfies git dependency `fc-cli` (locked to 1.0.0-dev) of package `tangle-standalone v0.4.2 (/Users/salman01zz/Webb-Tools/tangle/standalone/node)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='libsqlite3-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.
```

### PR DESCRIPTION
**Pull request by salman01zp**
## Summary of changes
- Handle subxt error
- Update lighthouse
- Update dkg to v0.4.4
- Update Tangle metadata to v0.4.4

### Reference issue to close (if applicable)
- Closes #60 
- Closes #61 
- Closes #54 

-----
### Code Checklist 

- [x] Tested
- [ ] Documented

### CODE REVIEW

File: crates/eth2-pallet-init/src/substrate_pallet_client.rs [hunk 1]
```diff
@@ -218,10 +218,21 @@ impl EthClientPallet {
 							return Ok(hash.0.into())
 						},
 						Err(err) => {
-							log::error!("tx failed {err:?}");
+							let error_msg = match err {
+								subxt::Error::Runtime(DispatchError::Module(error)) => {
+									let details = error.details()?;
+									let pallet = details.pallet.name();
+									let error = &details.variant.name;
+									format!("Extrinsic failed with an error: {pallet}::{error}")
```
Comment (shekohex) [inline crates/eth2-pallet-init/src/substrate_pallet_client.rs:226]: we should print the whole variant, as it may contain useful information like the message itself.

**Review by shekohex — CHANGES_REQUESTED** [review]

**Review by shekohex — APPROVED** [review]
